sudo: required
language: java
install: true 


services:
  - docker

jobs:
  include:
    - stage: build (compile, unit test, package)
      language: java
      jdk: openjdk11
      install: skip
      script: travis/build.sh

    - stage: container creation and publishing
      install: skip
      script: travis/containerCreation.sh

    - stage: smoke and acceptance test
      install: skip # without this there's a `git clone` and `gradlew assemble` executed!
      script: travis/acceptanceTest.sh

    - stage: release
      if: branch = master AND NOT type IN (pull_request)
      install: skip
      script: travis/release.sh

import:
  - docs/.travis.yml

notifications:
  slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
  email:
    recipients:
      - a.person@acme.com
      - a.n.other@acme.com
    on_success: never # default: change
    on_failure: never # default: always
